### ISSUE TITLE
通过二次 NAT 实现转发可能会简单很多

### ISSUE THREAD

**Issue by CrazyBoyFeng** [mightofcode/android-vpnservice#4]
我注意到这个项目几乎完整实现了 TCP 协议：手动进行握手挥手、用缓存处理 packet 到 socket 的组装（包括处理序号、重复包）。但是好像没有处理残包和粘包，没有校验收到的 TCP 包的有效性。要是把这些都做了，那就真的是完整的 TCP 协议了。  
但这样工作量是巨大的。不过有一种取巧的办法——二次 NAT，具体实现也很简单：
1. 在 app 里起一个位于 VPN 内部的 TCP server。
2. 从 tun 收到的 TCP 流量，如果发送者不是前述 TCP server，记录一下 `natSessions : Map<来源port,目的IP:目的port>`，修改目的为前述 TCP server 的 IP 和 port，写回 tun。（一次 NAT）
3. TCP server 收到一个 socket 连接。根据来源 port 查询 `natSessions`，得到目的 IP 和 port，建立与目的服务器的 socket 连接。然后将 TCP server 的 input 流重定向到真正服务器的 output 流上，output 流类同理。（二次 NAT）
4. 从 tun 收到的 TCP 流量，如果发送者是前述 TCP server，根据目的 port（原来源客户端 port）查询 `natSessions`，得到来源 IP 和 port（原目的服务器 IP 和 port），修改数据包来源，写回 tun。
5. 当连接关闭时，`natSessions` 做相应移除。

这样不用手动处理 TCP 包，不用实现 TCP 协议栈。

**Comment by mightofcode** [comment]
学习了

**Comment by Motel6** [comment]
> 我注意到这个项目几乎完整实现了 TCP 协议：手动进行握手挥手、用缓存处理 packet 到 socket 的组装（包括处理序号、重复包）。但是好像没有处理残包和粘包，没有校验收到的 TCP 包的有效性。要是把这些都做了，那就真的是完整的 TCP 协议了。
> 但这样工作量是巨大的。不过有一种取巧的办法——二次 NAT，具体实现也很简单：
> 
> 1. 在 app 里起一个位于 VPN 内部的 TCP server。
> 2. 从 tun 收到的 TCP 流量，如果发送者不是前述 TCP server，记录一下 `natSessions : Map<来源port,目的IP:目的port>`，修改目的为前述 TCP server 的 IP 和 port，写回 tun。（一次 NAT）
> 3. TCP server 收到一个 socket 连接。根据来源 port 查询 `natSessions`，得到目的 IP 和 port，建立与目的服务器的 socket 连接。然后将 TCP server 的 input 流重定向到真正服务器的 output 流上，output 流类同理。（二次 NAT）
> 4. 从 tun 收到的 TCP 流量，如果发送者是前述 TCP server，根据目的 port（原来源客户端 port）查询 `natSessions`，得到来源 IP 和 port（原目的服务器 IP 和 port），修改数据包来源，写回 tun。
> 5. 当连接关闭时，`natSessions` 做相应移除。
> 
> 这样不用手动处理 TCP 包，不用实现 TCP 协议栈。

第一次nat时，直接修改包的目的ip和目的port再写入tun0，tcp server的serverSocket似乎并不能accept到一个socket。
可以详细说一下实现吗？
it seems not to work like what you said, and im so curious now.
can you make it clearer? any advice and guidance is appreciated, thank you!

**Comment by CrazyBoyFeng** [comment]
tcp server 的 ip 得是 tun0 的 ip。
第一次直接修改包的目的 ip 也是到这个 tun0 的 ip 上。
可以参考 https://github.com/oldman1977/SmartProxy

**Comment by Motel6** [comment]
谢谢，我发现了原因。
> tcp server 的 ip 得是 tun0 的 ip。
经过验证发现并不是这样，serverSocket(或者serverSocketChannel) bind的ip并不必须为tun0的ip。
事实上我传给bind的ip是wlan0的地址。(即192.168.1.100) 也可以成功的。
猜测应该是只要在本机上可用的网络接口，都可以让server绑定。
我失败的原因是，第一次nat只修改了destination ip，而没有修改source ip。
若destination ip和source ip都在”本机局域网“内（如何判定是否在”本机局域网“内我还没有搞明白), tun0似乎会把写入的报文直接丢弃。**似乎tun0只会对destination ip和source ip不在"本机局域网”的network layer packet进行处理。**
解决办法：修改destination ip的同时修改source ip, 只要不让tun0认为source ip不在"本机局域网"内就行。我的应对方法是，把source ip改为第一个syn报文的destination ip(即用户真正请求的远程服务器的ip地址）。
i practiced a lot and find the solution，thanks for your information！
hope what i shared can do benifit for you too!

**Comment by CrazyBoyFeng** [comment]
确实是这样。我上面贴的那个项目也是这样写的：
https://github.com/oldman1977/SmartProxy/blob/f97e8b9cb96f41886c139dcfe986ac2d031d48c5/Smart%20Proxy%20X/src/main/java/me/smartproxy/core/LocalVpnService.java#L291

**Comment by Motel6** [comment]
> 确实是这样。我上面贴的那个项目也是这样写的：
> https://github.com/oldman1977/SmartProxy/blob/f97e8b9cb96f41886c139dcfe986ac2d031d48c5/Smart%20Proxy%20X/src/main/java/me/smartproxy/core/LocalVpnService.java#L291

well, after several days of trying, i have to admit that i failed.
it seems it only work during tcp handshake, and i really cant figure it out what is going in the following procedure
here is pcap grabbed by me:
 
![Screenshot 2021-08-16 163333](https://user-images.githubusercontent.com/26848012/129535143-c5fb9f56-ff60-48a6-a615-0802e37dd126.png)

you can see from the pic that the ip address i use to fake it as a remote server is 123.123.123.123 and i set up a serverSocketChannel at 192.1681.1.102(inet address of wlan0) with port designated with 2333.tun0 inet address is designated with 10.0.0.2.  

there are lots of things confusing in the pic, for example, i expect the third packet to be (192.168.1.102 -> syn,ack -> 123.123.123.123) , which then i can change the source ip:port back to real server 14.215.177.39:443 and dest ip to tun0 as the forth packet to be written to tun0, and dont know why it is (14.215.177.39 -> syn,ack -> 10.0.0.2).

following parts are also quiet confusing. i meant to put on a simple https test, however the tls process this conduct is not normal and failed after first client hello sent, as it is shown in the pic.

i guess this related to internal network address translation mechanism of tun0. and, just guess, havent read android source. although i digged into linux iproute2 and other network mechanism, i worried that android changed something.

i encountered a lot problem building the project you mentioned above, and if you succeed to implemented a little demo in this way, like a transparent proxy, it would be a *life saver* for me to share the source, and its also cool that you just want to reserve it. than u again for the information.

**Comment by CrazyBoyFeng** [comment]
Analyzing the problem without the code is difficult and can only be done by guessing.

The smartproxy above is a very old project, if it is not quite compatible with today's development environment, you can refer to [sagernet](https://github.com/SagerNet/SagerNet/tree/dev/app/src/main/java/io/nekohasekai/sagernet/tun).

**Comment by Motel6** [comment]
> Analyzing the problem without the code is difficult and can only be done by guessing.
> 
> The smartproxy above is a very old project, if it is not quite compatible with today's development environment, you can refer to [sagernet](https://github.com/SagerNet/SagerNet/tree/dev/app/src/main/java/io/nekohasekai/sagernet/tun).

thank u! but, my dear friend, it seems that sagernet is not implemented with manual nat mechanism, instead it use tun2socks lib as a user tcp stack.

**Comment by Motel6** [comment]
> > Analyzing the problem without the code is difficult and can only be done by guessing.
> > The smartproxy above is a very old project, if it is not quite compatible with today's development environment, you can refer to [sagernet](https://github.com/SagerNet/SagerNet/tree/dev/app/src/main/java/io/nekohasekai/sagernet/tun).
> 
> thank u! but, my dear friend, it seems that sagernet is not implemented with manual nat mechanism, instead it use tun2socks lib as a user tcp stack. or im wrong...are you sure it is based on nat?

**Comment by CrazyBoyFeng** [comment]
There are two implementations of tun to socks5 in sagernet, the `direct` implementation is nat-based. The code linked above is it.

**Comment by Motel6** [comment]
> There are two implementations of tun to socks5 in sagernet, the `direct` implementation is nat-based. The code linked above is it.

i tried it, in the settings set "VPN Mode" to Native Forwarding and "Other Internet Protocol Strategy" to Direct, and set up a vmess server in my laptop. the result is i got no access to internet.
im doubting its my phone's fault now 😢
