### ISSUE TITLE
我手里有后台给的密钥，用户名，密码，你这个怎么设置参数

### ISSUE THREAD

**Issue by liujieyuu** [mightofcode/android-vpnservice#6]
我手里有后台给的密钥，用户名，密码，你这个怎么设置参数

**Comment by mightofcode** [comment]
这是个简单的vpn例子 不涉及什么用户名密码



在 2021-04-09 11:58:26，"liujieyuu" ***@***.***> 写道：

我手里有后台给的密钥，用户名，密码，你这个怎么设置参数
